/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListsIndexRouteImport } from './routes/lists.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RiderDriverIdRouteImport } from './routes/rider.$driverId'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as OrderCallbackRouteImport } from './routes/order.callback'
import { Route as ListsIdRouteImport } from './routes/lists.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminZonesRouteImport } from './routes/admin.zones'
import { Route as AdminSettlementsRouteImport } from './routes/admin.settlements'
import { Route as AdminRiderPayRouteImport } from './routes/admin.rider-pay'
import { Route as AdminRefundRequestsRouteImport } from './routes/admin.refund-requests'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminDeliveriesRouteImport } from './routes/admin.deliveries'
import { Route as AdminCreditRouteImport } from './routes/admin.credit'
import { Route as AdminConsumerOrdersRouteImport } from './routes/admin.consumer-orders'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AccountRecurringRouteImport } from './routes/account.recurring'
import { Route as AccountCreditRouteImport } from './routes/account.credit'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'
import { Route as OrderIdIndexRouteImport } from './routes/order.$id.index'
import { Route as OrderIdConfirmationRouteImport } from './routes/order.$id.confirmation'
import { Route as ApiSessionStoreRouteImport } from './routes/api.session.store'
import { Route as ApiSessionRefreshRouteImport } from './routes/api.session.refresh'
import { Route as ApiSessionHandoffRouteImport } from './routes/api.session.handoff'
import { Route as ApiSessionClearRouteImport } from './routes/api.session.clear'
import { Route as ApiAuthRefreshRouteImport } from './routes/api.auth.refresh'
import { Route as ApiAuthLoginRouteImport } from './routes/api.auth.login'
import { Route as AdminProductIdPricesRouteImport } from './routes/admin.product.$id.prices'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIndexRoute = ListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderDriverIdRoute = RiderDriverIdRouteImport.update({
  id: '/rider/$driverId',
  path: '/rider/$driverId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderCallbackRoute = OrderCallbackRouteImport.update({
  id: '/order/callback',
  path: '/order/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIdRoute = ListsIdRouteImport.update({
  id: '/lists/$id',
  path: '/lists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminZonesRoute = AdminZonesRouteImport.update({
  id: '/admin/zones',
  path: '/admin/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettlementsRoute = AdminSettlementsRouteImport.update({
  id: '/admin/settlements',
  path: '/admin/settlements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRiderPayRoute = AdminRiderPayRouteImport.update({
  id: '/admin/rider-pay',
  path: '/admin/rider-pay',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRefundRequestsRoute = AdminRefundRequestsRouteImport.update({
  id: '/admin/refund-requests',
  path: '/admin/refund-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/admin/inventory',
  path: '/admin/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDeliveriesRoute = AdminDeliveriesRouteImport.update({
  id: '/admin/deliveries',
  path: '/admin/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreditRoute = AdminCreditRouteImport.update({
  id: '/admin/credit',
  path: '/admin/credit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConsumerOrdersRoute = AdminConsumerOrdersRouteImport.update({
  id: '/admin/consumer-orders',
  path: '/admin/consumer-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/admin/catalog',
  path: '/admin/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRecurringRoute = AccountRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => AccountRoute,
} as any)
const AccountCreditRoute = AccountCreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const OrderIdIndexRoute = OrderIdIndexRouteImport.update({
  id: '/order/$id/',
  path: '/order/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdConfirmationRoute = OrderIdConfirmationRouteImport.update({
  id: '/order/$id/confirmation',
  path: '/order/$id/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionStoreRoute = ApiSessionStoreRouteImport.update({
  id: '/api/session/store',
  path: '/api/session/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRefreshRoute = ApiSessionRefreshRouteImport.update({
  id: '/api/session/refresh',
  path: '/api/session/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionHandoffRoute = ApiSessionHandoffRouteImport.update({
  id: '/api/session/handoff',
  path: '/api/session/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionClearRoute = ApiSessionClearRouteImport.update({
  id: '/api/session/clear',
  path: '/api/session/clear',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRefreshRoute = ApiAuthRefreshRouteImport.update({
  id: '/api/auth/refresh',
  path: '/api/auth/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductIdPricesRoute = AdminProductIdPricesRouteImport.update({
  id: '/admin/product/$id/prices',
  path: '/admin/product/$id/prices',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/credit': typeof AccountCreditRoute
  '/account/recurring': typeof AccountRecurringRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/consumer-orders': typeof AdminConsumerOrdersRoute
  '/admin/credit': typeof AdminCreditRoute
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/refund-requests': typeof AdminRefundRequestsRoute
  '/admin/rider-pay': typeof AdminRiderPayRoute
  '/admin/settlements': typeof AdminSettlementsRoute
  '/admin/zones': typeof AdminZonesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/category/$slug': typeof CategorySlugRoute
  '/lists/$id': typeof ListsIdRoute
  '/order/callback': typeof OrderCallbackRoute
  '/product/$slug': typeof ProductSlugRoute
  '/rider/$driverId': typeof RiderDriverIdRoute
  '/admin/': typeof AdminIndexRoute
  '/lists/': typeof ListsIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/session/clear': typeof ApiSessionClearRoute
  '/api/session/handoff': typeof ApiSessionHandoffRoute
  '/api/session/refresh': typeof ApiSessionRefreshRoute
  '/api/session/store': typeof ApiSessionStoreRoute
  '/order/$id/confirmation': typeof OrderIdConfirmationRoute
  '/order/$id/': typeof OrderIdIndexRoute
  '/admin/product/$id/prices': typeof AdminProductIdPricesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/credit': typeof AccountCreditRoute
  '/account/recurring': typeof AccountRecurringRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/consumer-orders': typeof AdminConsumerOrdersRoute
  '/admin/credit': typeof AdminCreditRoute
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/refund-requests': typeof AdminRefundRequestsRoute
  '/admin/rider-pay': typeof AdminRiderPayRoute
  '/admin/settlements': typeof AdminSettlementsRoute
  '/admin/zones': typeof AdminZonesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/category/$slug': typeof CategorySlugRoute
  '/lists/$id': typeof ListsIdRoute
  '/order/callback': typeof OrderCallbackRoute
  '/product/$slug': typeof ProductSlugRoute
  '/rider/$driverId': typeof RiderDriverIdRoute
  '/admin': typeof AdminIndexRoute
  '/lists': typeof ListsIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/session/clear': typeof ApiSessionClearRoute
  '/api/session/handoff': typeof ApiSessionHandoffRoute
  '/api/session/refresh': typeof ApiSessionRefreshRoute
  '/api/session/store': typeof ApiSessionStoreRoute
  '/order/$id/confirmation': typeof OrderIdConfirmationRoute
  '/order/$id': typeof OrderIdIndexRoute
  '/admin/product/$id/prices': typeof AdminProductIdPricesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/credit': typeof AccountCreditRoute
  '/account/recurring': typeof AccountRecurringRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/consumer-orders': typeof AdminConsumerOrdersRoute
  '/admin/credit': typeof AdminCreditRoute
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/refund-requests': typeof AdminRefundRequestsRoute
  '/admin/rider-pay': typeof AdminRiderPayRoute
  '/admin/settlements': typeof AdminSettlementsRoute
  '/admin/zones': typeof AdminZonesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/category/$slug': typeof CategorySlugRoute
  '/lists/$id': typeof ListsIdRoute
  '/order/callback': typeof OrderCallbackRoute
  '/product/$slug': typeof ProductSlugRoute
  '/rider/$driverId': typeof RiderDriverIdRoute
  '/admin/': typeof AdminIndexRoute
  '/lists/': typeof ListsIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/session/clear': typeof ApiSessionClearRoute
  '/api/session/handoff': typeof ApiSessionHandoffRoute
  '/api/session/refresh': typeof ApiSessionRefreshRoute
  '/api/session/store': typeof ApiSessionStoreRoute
  '/order/$id/confirmation': typeof OrderIdConfirmationRoute
  '/order/$id/': typeof OrderIdIndexRoute
  '/admin/product/$id/prices': typeof AdminProductIdPricesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/login'
    | '/notifications'
    | '/orders'
    | '/products'
    | '/search'
    | '/sitemap.xml'
    | '/account/addresses'
    | '/account/credit'
    | '/account/recurring'
    | '/admin/catalog'
    | '/admin/categories'
    | '/admin/consumer-orders'
    | '/admin/credit'
    | '/admin/deliveries'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/refund-requests'
    | '/admin/rider-pay'
    | '/admin/settlements'
    | '/admin/zones'
    | '/auth/callback'
    | '/category/$slug'
    | '/lists/$id'
    | '/order/callback'
    | '/product/$slug'
    | '/rider/$driverId'
    | '/admin/'
    | '/lists/'
    | '/api/auth/login'
    | '/api/auth/refresh'
    | '/api/session/clear'
    | '/api/session/handoff'
    | '/api/session/refresh'
    | '/api/session/store'
    | '/order/$id/confirmation'
    | '/order/$id/'
    | '/admin/product/$id/prices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/login'
    | '/notifications'
    | '/orders'
    | '/products'
    | '/search'
    | '/sitemap.xml'
    | '/account/addresses'
    | '/account/credit'
    | '/account/recurring'
    | '/admin/catalog'
    | '/admin/categories'
    | '/admin/consumer-orders'
    | '/admin/credit'
    | '/admin/deliveries'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/refund-requests'
    | '/admin/rider-pay'
    | '/admin/settlements'
    | '/admin/zones'
    | '/auth/callback'
    | '/category/$slug'
    | '/lists/$id'
    | '/order/callback'
    | '/product/$slug'
    | '/rider/$driverId'
    | '/admin'
    | '/lists'
    | '/api/auth/login'
    | '/api/auth/refresh'
    | '/api/session/clear'
    | '/api/session/handoff'
    | '/api/session/refresh'
    | '/api/session/store'
    | '/order/$id/confirmation'
    | '/order/$id'
    | '/admin/product/$id/prices'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/login'
    | '/notifications'
    | '/orders'
    | '/products'
    | '/search'
    | '/sitemap.xml'
    | '/account/addresses'
    | '/account/credit'
    | '/account/recurring'
    | '/admin/catalog'
    | '/admin/categories'
    | '/admin/consumer-orders'
    | '/admin/credit'
    | '/admin/deliveries'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/refund-requests'
    | '/admin/rider-pay'
    | '/admin/settlements'
    | '/admin/zones'
    | '/auth/callback'
    | '/category/$slug'
    | '/lists/$id'
    | '/order/callback'
    | '/product/$slug'
    | '/rider/$driverId'
    | '/admin/'
    | '/lists/'
    | '/api/auth/login'
    | '/api/auth/refresh'
    | '/api/session/clear'
    | '/api/session/handoff'
    | '/api/session/refresh'
    | '/api/session/store'
    | '/order/$id/confirmation'
    | '/order/$id/'
    | '/admin/product/$id/prices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  ProductsRoute: typeof ProductsRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminConsumerOrdersRoute: typeof AdminConsumerOrdersRoute
  AdminCreditRoute: typeof AdminCreditRoute
  AdminDeliveriesRoute: typeof AdminDeliveriesRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminRefundRequestsRoute: typeof AdminRefundRequestsRoute
  AdminRiderPayRoute: typeof AdminRiderPayRoute
  AdminSettlementsRoute: typeof AdminSettlementsRoute
  AdminZonesRoute: typeof AdminZonesRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ListsIdRoute: typeof ListsIdRoute
  OrderCallbackRoute: typeof OrderCallbackRoute
  ProductSlugRoute: typeof ProductSlugRoute
  RiderDriverIdRoute: typeof RiderDriverIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ListsIndexRoute: typeof ListsIndexRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthRefreshRoute: typeof ApiAuthRefreshRoute
  ApiSessionClearRoute: typeof ApiSessionClearRoute
  ApiSessionHandoffRoute: typeof ApiSessionHandoffRoute
  ApiSessionRefreshRoute: typeof ApiSessionRefreshRoute
  ApiSessionStoreRoute: typeof ApiSessionStoreRoute
  OrderIdConfirmationRoute: typeof OrderIdConfirmationRoute
  OrderIdIndexRoute: typeof OrderIdIndexRoute
  AdminProductIdPricesRoute: typeof AdminProductIdPricesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/': {
      id: '/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof ListsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/$driverId': {
      id: '/rider/$driverId'
      path: '/rider/$driverId'
      fullPath: '/rider/$driverId'
      preLoaderRoute: typeof RiderDriverIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/callback': {
      id: '/order/callback'
      path: '/order/callback'
      fullPath: '/order/callback'
      preLoaderRoute: typeof OrderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/$id': {
      id: '/lists/$id'
      path: '/lists/$id'
      fullPath: '/lists/$id'
      preLoaderRoute: typeof ListsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/zones': {
      id: '/admin/zones'
      path: '/admin/zones'
      fullPath: '/admin/zones'
      preLoaderRoute: typeof AdminZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settlements': {
      id: '/admin/settlements'
      path: '/admin/settlements'
      fullPath: '/admin/settlements'
      preLoaderRoute: typeof AdminSettlementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rider-pay': {
      id: '/admin/rider-pay'
      path: '/admin/rider-pay'
      fullPath: '/admin/rider-pay'
      preLoaderRoute: typeof AdminRiderPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/refund-requests': {
      id: '/admin/refund-requests'
      path: '/admin/refund-requests'
      fullPath: '/admin/refund-requests'
      preLoaderRoute: typeof AdminRefundRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/deliveries': {
      id: '/admin/deliveries'
      path: '/admin/deliveries'
      fullPath: '/admin/deliveries'
      preLoaderRoute: typeof AdminDeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/credit': {
      id: '/admin/credit'
      path: '/admin/credit'
      fullPath: '/admin/credit'
      preLoaderRoute: typeof AdminCreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/consumer-orders': {
      id: '/admin/consumer-orders'
      path: '/admin/consumer-orders'
      fullPath: '/admin/consumer-orders'
      preLoaderRoute: typeof AdminConsumerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/admin/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/recurring': {
      id: '/account/recurring'
      path: '/recurring'
      fullPath: '/account/recurring'
      preLoaderRoute: typeof AccountRecurringRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/credit': {
      id: '/account/credit'
      path: '/credit'
      fullPath: '/account/credit'
      preLoaderRoute: typeof AccountCreditRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/order/$id/': {
      id: '/order/$id/'
      path: '/order/$id'
      fullPath: '/order/$id/'
      preLoaderRoute: typeof OrderIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id/confirmation': {
      id: '/order/$id/confirmation'
      path: '/order/$id/confirmation'
      fullPath: '/order/$id/confirmation'
      preLoaderRoute: typeof OrderIdConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session/store': {
      id: '/api/session/store'
      path: '/api/session/store'
      fullPath: '/api/session/store'
      preLoaderRoute: typeof ApiSessionStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session/refresh': {
      id: '/api/session/refresh'
      path: '/api/session/refresh'
      fullPath: '/api/session/refresh'
      preLoaderRoute: typeof ApiSessionRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session/handoff': {
      id: '/api/session/handoff'
      path: '/api/session/handoff'
      fullPath: '/api/session/handoff'
      preLoaderRoute: typeof ApiSessionHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session/clear': {
      id: '/api/session/clear'
      path: '/api/session/clear'
      fullPath: '/api/session/clear'
      preLoaderRoute: typeof ApiSessionClearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/refresh': {
      id: '/api/auth/refresh'
      path: '/api/auth/refresh'
      fullPath: '/api/auth/refresh'
      preLoaderRoute: typeof ApiAuthRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/product/$id/prices': {
      id: '/admin/product/$id/prices'
      path: '/admin/product/$id/prices'
      fullPath: '/admin/product/$id/prices'
      preLoaderRoute: typeof AdminProductIdPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountCreditRoute: typeof AccountCreditRoute
  AccountRecurringRoute: typeof AccountRecurringRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountCreditRoute: AccountCreditRoute,
  AccountRecurringRoute: AccountRecurringRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  ProductsRoute: ProductsRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminConsumerOrdersRoute: AdminConsumerOrdersRoute,
  AdminCreditRoute: AdminCreditRoute,
  AdminDeliveriesRoute: AdminDeliveriesRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminRefundRequestsRoute: AdminRefundRequestsRoute,
  AdminRiderPayRoute: AdminRiderPayRoute,
  AdminSettlementsRoute: AdminSettlementsRoute,
  AdminZonesRoute: AdminZonesRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CategorySlugRoute: CategorySlugRoute,
  ListsIdRoute: ListsIdRoute,
  OrderCallbackRoute: OrderCallbackRoute,
  ProductSlugRoute: ProductSlugRoute,
  RiderDriverIdRoute: RiderDriverIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ListsIndexRoute: ListsIndexRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthRefreshRoute: ApiAuthRefreshRoute,
  ApiSessionClearRoute: ApiSessionClearRoute,
  ApiSessionHandoffRoute: ApiSessionHandoffRoute,
  ApiSessionRefreshRoute: ApiSessionRefreshRoute,
  ApiSessionStoreRoute: ApiSessionStoreRoute,
  OrderIdConfirmationRoute: OrderIdConfirmationRoute,
  OrderIdIndexRoute: OrderIdIndexRoute,
  AdminProductIdPricesRoute: AdminProductIdPricesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
